name: "ci-main smoke"
on:
  push:
jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "runner up"
      - name: Python env
        run: |
          python3 --version || true
          pip3 --version || true
