name: "ci-main smoke+validators"
on:
  push:
jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "runner up"

      - name: Python env
        run: |
          python3 --version || true
          pip3 --version || true
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user pyyaml jsonschema || true

      - name: Fetch repo via codeload (public, retry)
        run: |
          set -e
          rm -rf work && mkdir -p work
          curl --retry 6 --retry-delay 2 -L -o src.zip "https://codeload.github.com/fleet1735/Endeavour/zip/refs/heads/main"
          unzip -q src.zip -d work
          mv work/Endeavour-main work/src
          ls -la work/src | head -n 20 || true

      - name: Run CF-ONT-101..105
        run: |
          set -e
          cd work/src
          python3 tools/ci/cf_101.py

      - name: Run CF-ONT-201
        run: |
          set -e
          cd work/src
          python3 tools/ci/cf_201.py

      - name: Summarize → step summary & exit
        run: |
          set -e
          cd work/src
          python3 tools/ci/summarize.py
