name: Endeavour CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PowerShell
        uses: PowerShell/actions-setup-pwsh@v2

      - name: Install Python (for other steps if needed)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ---------- Sprint 4 Validator: Gate 이전 사전 검증 ----------
      - name: Run Sprint4 Validator v1
        shell: pwsh
        run: |
          pwsh -NoLogo -NoProfile -File .\scripts\validator_v1.ps1

      # ---------- 아래에 기존 Gate/Build/Test 단계가 온다고 가정 ----------
      - name: Build / Test (placeholder)
        shell: pwsh
        run: |
          Write-Host "Build/Test steps go here."