name: "ci(ontology): parser-smoke"
on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/ontology_ci.yml"
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "workflow parser OK"