name: "ci(ontology): main(push) — calls core"
on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/ontology_ci_main.yml"
      - ".github/workflows/ontology_ci_core.yml"
      - "validator/**"
      - "schemas/**"
      - "registry.yaml"
      - "registry.yml"
      - "runs/**"
      - "engine/**"
      - "setups/**"
permissions:
  contents: read
  actions: write
jobs:
  call_core:
    uses: fleet1735/Endeavour/.github/workflows/ontology_ci_core.yml@main
